### PR TITLE
Update minimal.yaml

### PR DESCRIPTION
**Pull request by HidYn**
Added ota platform due to breaking changes with ESPHome 2024.6

https://esphome.io/changelog/2024.6.0

### CODE REVIEW

**Comment by jburgess777** [comment]
The changelog implied the ‘platform’ field should be indented:
https://esphome.io/changelog/2024.6.0.html#ota-platforms

**Review by gavindekock — APPROVED** [review]

**Comment by AAllport** [comment]
Forgot we had setup gha 🤦
That error looks like it's on the pipeline, not the change.

Thanks for the contribution, @HidYn 
Merging :)

**Comment by gavindekock** [comment]
The build error seems to be related to https://github.com/esphome/build-action/issues/34 also affecting the copy of publish in your fork called https://github.com/LocalBytes/esphome-localbytes-plug/blob/main/.github/workflows/publish-esphome.yml

**Comment by jburgess777** [comment]
The new 1.2.0 release compiled and installed successfully for me:

INFO ESPHome 2024.6.3
INFO Reading configuration /config/esphome/localbytes-plug-pm-8ca2e6.yaml...
INFO Starting log output from 192.168.1.208 using esphome API
INFO Successfully connected to localbytes-plug-pm-8ca2e6 @ 192.168.1.208 in 0.026s
INFO Successful handshake with localbytes-plug-pm-8ca2e6 @ 192.168.1.208 in 2.662s
[21:14:12][I][app:100]: ESPHome version 2024.6.3 compiled on Jun 26 2024, 20:53:33
[21:14:13][I][app:102]: Project localbytes.plug-pm version 1.2.0
[21:14:13][C][wifi:599]: WiFi:
...

**Pull request merged**
